### ISSUE TITLE
Loveyl it, however - it doesn't work for me

### ISSUE THREAD

**Issue by DangerZoneDuchess** [dragstor/shottr-alfred-workflow#1]
Apple M2 Chip, OS Sequoia 15.0 , Using Alfred 5.5.1 (2273) - installed the workflow and tried to execute commands. While they appear in the Alfred Search bar, nothing happens when executing them. It doesn't matter if shottr is already working in the background or not.

**Comment by dragstor** [comment]
> Apple M2 Chip, OS Sequoia 15.0 , Using Alfred 5.5.1 (2273) - installed the workflow and tried to execute commands. While they appear in the Alfred Search bar, nothing happens when executing them. It doesn't matter if shottr is already working in the background or not.

Thanks for reporting! 🙌🏼 

Can you try this one, please:

- https://drive.google.com/file/d/1m3u3VPzNFmGSMp2ckPA7DCADBaILgIF4/view?usp=drive_link

If it works, the issue was that I initially used `/bin/bash` instead of the default one, `/bin/zsh` 😅

**Comment by DangerZoneDuchess** [comment]
That unfortunately also didn't work on my side :-)

**Comment by dragstor** [comment]
Thank you for trying!

Can you please activate the workflow's Debugging view and try using some of the workflow keywords to see if there are any specific issues?

![image](https://github.com/user-attachments/assets/026ee87d-e7c8-4262-b2c8-10088eb45529)

**Comment by dragstor** [comment]
And I just realized — are you using Shottr v1.7.2? :)

If so, please update to v1.8 and retry: https://shottr.cc/dl/Shottr-1.8.0.dmg 📦 👍🏼

**Comment by DangerZoneDuchess** [comment]
🙈 🤦 
Thanks! It was that last bit!

**Comment by DangerZoneDuchess** [comment]
As usual, the problem is between the screen and the chair.
