### ISSUE TITLE
No configurations in the workflow

### ISSUE THREAD

**Issue by pearresearch** [dragstor/shottr-alfred-workflow#2]
The Alfred workflow is blank for me. Am I setting it up wrongly? v1.0.1

**Comment by dragstor** [comment]
> The Alfred workflow is blank for me. Am I setting it up wrongly? v1.0.1

Hey 👋🏼 

After downloading it from the [v1.0.1 release](https://github.com/dragstor/shottr-alfred-workflow/releases/download/v1.0.1/Shottr.cc.alfredworkflow) and double-clicking it, does it load in Alfred at all?
![image](https://github.com/user-attachments/assets/3580f87c-9034-46af-abf0-1f0c401a8559)


If it does, verify it's working by using the `ssa` keyword, for example.

It should offer you this:

![image](https://github.com/user-attachments/assets/cce1543f-e6e9-47f6-8d10-a04d703b802c)

**Comment by dragstor** [comment]
Also, ensure you're using the latest Shottr (v1.8): https://shottr.cc/dl/Shottr-1.8.0.dmg 😄

**Comment by pearresearch** [comment]
You know, that was dumb of me, I guess. I did see it now. Previously it simply had nothing in the workflow.
